### ISSUE TITLE
dodanie partnera

### ISSUE THREAD

**Issue by yoganka** [MMadejsza/yoganka.pl#59]
### 📝 Task Description

Limitless oraz Witramowo 32 

### 📌 Expectations Bullet Points

Brak

### 📆 How urgent it is?

💥 ASAP

### 📷 Have you uploaded all necessary media/files to Google Disk?

💪 Yes

**Comment by MMadejsza** [comment]
Limitless logo added + tuned up the image quality of all the rest.
