### ISSUE TITLE
Change tittle 

### ISSUE THREAD

**Issue by yoganka** [MMadejsza/yoganka.pl#65]
### 📝 Task Description

to change "wyjazdy slow" into "kobiece wyjazdy z jogą"

### 📌 Expectations Bullet Points

- [ ] change the font size?

### 📆 How urgent is it?

☝️ 1-2 weeks

### 📷 Have you uploaded all necessary media/files to Google Disk?

💪 Yes

**Comment by MMadejsza** [comment]
Font size bigger? or smaller?

**Comment by MMadejsza** [comment]
Title changed. Font size remained.
